<?php

namespace Tests\Feature\Admin\Roles;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class IndexRoleTest extends TestCase
{
    use RefreshDatabase;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed --class=PermissionsSeeder');
    }

    public function test_it_can_list_roles(): void
    {
        $user = User::factory()->create()->givePermissionTo('see-rol');
        $response = $this->actingAs($user)->get(route('roles.index'));
        $response->assertStatus(200);
        $response->assertViewIs('roles.index');
        $response->assertViewHas('roles');
    }

    public function test_it_user_doesnt_permissions_cant_list_users(): void
    {
        $user2 = User::factory()->create();
        $response = $this->actingAs($user2)->get(route('roles.index'));
        $response->assertForbidden();
    }
}
