<?php

namespace Tests\Feature\Admin\Roles;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Arr;
use Tests\TestCase;

class StoreRoleTest extends TestCase
{
    use RefreshDatabase;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed --class=PermissionsSeeder');
    }

    public function test_it_can_stores_a_new_role(): void
    {
        $data = [
            'name' => 'admin test',
            'permission' => 'create-user'
        ];

        $user = User::factory()->create()->givePermissionTo('create-rol');
        $response = $this->actingAs($user)->post(route('roles.store'), $data);
        $response->assertRedirect();
        $this->assertDatabaseHas('roles', Arr::only($data,['name']));
    }

}
