<?php

namespace Tests\Feature\Admin\Products;

use App\Models\Product;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Http\UploadedFile;
use Tests\TestCase;

class DeleteProductTest extends TestCase
{
    use RefreshDatabase;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed --class=PermissionsSeeder');
    }
    public function test_it_can_delete_products(): void
    {
        $data = Product::factory()->create();
        $user = User::factory()->create()->givePermissionTo('delete-product');
        $response = $this->actingAs($user)->delete("/admin/products/{$data->id}");
        $response->assertRedirect();
    }
}
