<?php

namespace Tests\Feature\Admin\Products;

use App\Models\Product;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ShowProductTest extends TestCase
{
    use RefreshDatabase;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed --class=PermissionsSeeder');
    }
    public function test_it_can_show_product(): void
    {
        $product = Product::factory()->create();
        $user = User::factory()->create()->givePermissionTo('edit-product');
        $response = $this->actingAs($user)->get("/products/{$product->id}");
        $response->assertStatus(200);
        $response->assertViewIs('admin.products.show');
        $response->assertViewHas('product');
    }
}
