<?php

namespace Tests\Feature\Admin\Actions;

use App\Models\Product;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ChangeProductStatusTest extends TestCase
{
    use RefreshDatabase;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed --class=PermissionsSeeder');
    }

    public function test_it_can_change_product_status_to_desabled(): void
    {
        $product = Product::factory()->create();
        $user = User::factory()->create()->givePermissionTo('edit-product');
        $response = $this->actingAs($user)->put(route('changeProductStatus', $product->id));
        $response->assertRedirect();

        $product = $product->refresh();
        $this->assertEquals($product['disabled_at'], Carbon::now());
    }

    public function test_it_can_change_product_status_to_enabled(): void
    {
        $product = Product::factory()->create();
        $user = User::factory()->create()->givePermissionTo('edit-product');
        $this->actingAs($user)->put(route('changeProductStatus', $product->id));
        $response = $this->actingAs($user)->put(route('changeProductStatus', $product->id));
        $response->assertRedirect();

        $product = $product->refresh();
        $this->assertEquals($product['disabled_at'], null);
    }
}
